version: 2.1

jobs:
  cypress-test:
    docker:
      - image: cypress/base:16
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Cypress binary
          command: npx cypress install
      - run:
          name: Run Cypress tests
          command: npx cypress run --record --parallel --key $CYPRESS_RECORD_KEY

workflows:
  version: 2
  test:
    jobs:
      - cypress-test
          
